language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

install:
  - mvn clean compile -DskipTests
  - mvn test
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn install -DskipTests -Pdefault,docker
  - mvn deploy -DskipTests -Pdocker

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  - docker tag marketreaction/api:$TRAVIS_BUILD_NUMBER marketreaction/api:latest
  - docker tag marketreaction/api:${TRAVIS_BUILD_NUMBER}-x86 marketreaction/api:latest-x86
  - docker push marketreaction/api:latest
  - docker push marketreaction/api:latest-x86
